//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classificationScheme",
    "classificationSchemeItemName",
    "classificationSchemeItemType",
    "csiPublicId",
    "csiVersion"
})
@XmlRootElement(name = "CLASSIFICATIONSLIST_ITEM")
public class Classification {

    @XmlElement(name = "ClassificationScheme", required = true)
    protected ClassificationScheme classificationScheme;
    @XmlElement(name = "ClassificationSchemeItemName", required = true)
    protected String classificationSchemeItemName;
    @XmlElement(name = "ClassificationSchemeItemType", required = true)
    protected String classificationSchemeItemType;
    @XmlElement(name = "CsiPublicId", required = true)
    protected String csiPublicId;
    @XmlElement(name = "CsiVersion", required = true)
    protected String csiVersion;

    /**
     * Gets the value of the classificationScheme property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationScheme }
     *     
     */
    public ClassificationScheme getClassificationScheme() {
        return classificationScheme;
    }

    /**
     * Sets the value of the classificationScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationScheme }
     *     
     */
    public void setClassificationScheme(ClassificationScheme value) {
        this.classificationScheme = value;
    }

    /**
     * Gets the value of the classificationSchemeItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationSchemeItemName() {
        return classificationSchemeItemName;
    }

    /**
     * Sets the value of the classificationSchemeItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationSchemeItemName(String value) {
        this.classificationSchemeItemName = value;
    }

    /**
     * Gets the value of the classificationSchemeItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationSchemeItemType() {
        return classificationSchemeItemType;
    }

    /**
     * Sets the value of the classificationSchemeItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationSchemeItemType(String value) {
        this.classificationSchemeItemType = value;
    }

    /**
     * Gets the value of the csiPublicId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsiPublicId() {
        return csiPublicId;
    }

    /**
     * Sets the value of the csiPublicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsiPublicId(String value) {
        this.csiPublicId = value;
    }

    /**
     * Gets the value of the csiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsiVersion() {
        return csiVersion;
    }

    /**
     * Sets the value of the csiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsiVersion(String value) {
        this.csiVersion = value;
    }

}
