//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publicId",
    "preferredName",
    "preferredDefinition",
    "longName",
    "version",
    "workflowStatus",
    "contextName",
    "contextVersion",
    "conceptualDomain",
    "objectClass",
    "property",
    "objectClassQualifier",
    "propertyQualifier",
    "origin"
})
@XmlRootElement(name = "DATAELEMENTCONCEPT")
public class DataElementConcept {

    @XmlElement(name = "PublicId", required = true)
    protected PublicId publicId;
    @XmlElement(name = "PreferredName", required = true)
    protected PreferredName preferredName;
    @XmlElement(name = "PreferredDefinition", required = true)
    protected String preferredDefinition;
    @XmlElement(name = "LongName", required = true)
    protected LongName longName;
    @XmlElement(name = "Version", required = true)
    protected Version version;
    @XmlElement(name = "WorkflowStatus", required = true)
    protected String workflowStatus;
    @XmlElement(name = "ContextName", required = true)
    protected ContextName contextName;
    @XmlElement(name = "ContextVersion", required = true)
    protected ContextVersion contextVersion;
    @XmlElement(name = "ConceptualDomain", required = true)
    protected ConceptualDomain conceptualDomain;
    @XmlElement(name = "ObjectClass", required = true)
    protected ObjectClass objectClass;
    @XmlElement(name = "Property", required = true)
    protected Property property;
    @XmlElement(name = "ObjectClassQualifier", required = true)
    protected ObjectClassQualifier objectClassQualifier;
    @XmlElement(name = "PropertyQualifier", required = true)
    protected PropertyQualifier propertyQualifier;
    @XmlElement(name = "Origin", required = true)
    protected Origin origin;

    /**
     * Gets the value of the publicId property.
     * 
     * @return
     *     possible object is
     *     {@link PublicId }
     *     
     */
    public PublicId getPublicId() {
        return publicId;
    }

    /**
     * Sets the value of the publicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicId }
     *     
     */
    public void setPublicId(PublicId value) {
        this.publicId = value;
    }

    /**
     * Gets the value of the preferredName property.
     * 
     * @return
     *     possible object is
     *     {@link PreferredName }
     *     
     */
    public PreferredName getPreferredName() {
        return preferredName;
    }

    /**
     * Sets the value of the preferredName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferredName }
     *     
     */
    public void setPreferredName(PreferredName value) {
        this.preferredName = value;
    }

    /**
     * Gets the value of the preferredDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredDefinition() {
        return preferredDefinition;
    }

    /**
     * Sets the value of the preferredDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredDefinition(String value) {
        this.preferredDefinition = value;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link LongName }
     *     
     */
    public LongName getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongName }
     *     
     */
    public void setLongName(LongName value) {
        this.longName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Version }
     *     
     */
    public Version getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Version }
     *     
     */
    public void setVersion(Version value) {
        this.version = value;
    }

    /**
     * Gets the value of the workflowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowStatus() {
        return workflowStatus;
    }

    /**
     * Sets the value of the workflowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowStatus(String value) {
        this.workflowStatus = value;
    }

    /**
     * Gets the value of the contextName property.
     * 
     * @return
     *     possible object is
     *     {@link ContextName }
     *     
     */
    public ContextName getContextName() {
        return contextName;
    }

    /**
     * Sets the value of the contextName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextName }
     *     
     */
    public void setContextName(ContextName value) {
        this.contextName = value;
    }

    /**
     * Gets the value of the contextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ContextVersion }
     *     
     */
    public ContextVersion getContextVersion() {
        return contextVersion;
    }

    /**
     * Sets the value of the contextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextVersion }
     *     
     */
    public void setContextVersion(ContextVersion value) {
        this.contextVersion = value;
    }

    /**
     * Gets the value of the conceptualDomain property.
     * 
     * @return
     *     possible object is
     *     {@link ConceptualDomain }
     *     
     */
    public ConceptualDomain getConceptualDomain() {
        return conceptualDomain;
    }

    /**
     * Sets the value of the conceptualDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConceptualDomain }
     *     
     */
    public void setConceptualDomain(ConceptualDomain value) {
        this.conceptualDomain = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectClass }
     *     
     */
    public ObjectClass getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectClass }
     *     
     */
    public void setObjectClass(ObjectClass value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link Property }
     *     
     */
    public Property getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link Property }
     *     
     */
    public void setProperty(Property value) {
        this.property = value;
    }

    /**
     * Gets the value of the objectClassQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectClassQualifier }
     *     
     */
    public ObjectClassQualifier getObjectClassQualifier() {
        return objectClassQualifier;
    }

    /**
     * Sets the value of the objectClassQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectClassQualifier }
     *     
     */
    public void setObjectClassQualifier(ObjectClassQualifier value) {
        this.objectClassQualifier = value;
    }

    /**
     * Gets the value of the propertyQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyQualifier }
     *     
     */
    public PropertyQualifier getPropertyQualifier() {
        return propertyQualifier;
    }

    /**
     * Sets the value of the propertyQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyQualifier }
     *     
     */
    public void setPropertyQualifier(PropertyQualifier value) {
        this.propertyQualifier = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Origin }
     *     
     */
    public Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origin }
     *     
     */
    public void setOrigin(Origin value) {
        this.origin = value;
    }

}
