//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publicId",
    "preferredName",
    "preferredDefinition",
    "longName",
    "version",
    "workflowStatus",
    "contextName",
    "contextVersion",
    "conceptualDomain",
    "datatype",
    "valueDomainType",
    "unitOfMeasure",
    "displayFormat",
    "maximumLength",
    "minimumLength",
    "decimalPlace",
    "characterSetName",
    "maximumValue",
    "minimumValue",
    "origin",
    "representation",
    "permissibleValues",
    "valueDomainConcepts"
})
@XmlRootElement(name = "VALUEDOMAIN")
public class ValueDomain {

    @XmlElement(name = "PublicId", required = true)
    protected PublicId publicId;
    @XmlElement(name = "PreferredName", required = true)
    protected PreferredName preferredName;
    @XmlElement(name = "PreferredDefinition", required = true)
    protected String preferredDefinition;
    @XmlElement(name = "LongName", required = true)
    protected LongName longName;
    @XmlElement(name = "Version", required = true)
    protected Version version;
    @XmlElement(name = "WorkflowStatus", required = true)
    protected String workflowStatus;
    @XmlElement(name = "ContextName", required = true)
    protected ContextName contextName;
    @XmlElement(name = "ContextVersion", required = true)
    protected ContextVersion contextVersion;
    @XmlElement(name = "ConceptualDomain", required = true)
    protected ConceptualDomain conceptualDomain;
    @XmlElement(name = "Datatype", required = true)
    protected String datatype;
    @XmlElement(name = "ValueDomainType", required = true)
    protected String valueDomainType;
    @XmlElement(name = "UnitOfMeasure", required = true)
    protected UnitOfMeasure unitOfMeasure;
    @XmlElement(name = "DisplayFormat", required = true)
    protected DisplayFormat displayFormat;
    @XmlElement(name = "MaximumLength", required = true)
    protected MaximumLength maximumLength;
    @XmlElement(name = "MinimumLength", required = true)
    protected MinimumLength minimumLength;
    @XmlElement(name = "DecimalPlace", required = true)
    protected DecimalPlace decimalPlace;
    @XmlElement(name = "CharacterSetName", required = true)
    protected CharacterSetName characterSetName;
    @XmlElement(name = "MaximumValue", required = true)
    protected MaximumValue maximumValue;
    @XmlElement(name = "MinimumValue", required = true)
    protected MinimumValue minimumValue;
    @XmlElement(name = "Origin", required = true)
    protected Origin origin;
    @XmlElement(name = "Representation", required = true)
    protected Representation representation;
    @XmlElement(name = "PermissibleValues", required = true)
    protected PermissibleValues permissibleValues;
    @XmlElement(name = "ValueDomainConcepts", required = true)
    protected ValueDomainConcepts valueDomainConcepts;

    /**
     * Gets the value of the publicId property.
     * 
     * @return
     *     possible object is
     *     {@link PublicId }
     *     
     */
    public PublicId getPublicId() {
        return publicId;
    }

    /**
     * Sets the value of the publicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicId }
     *     
     */
    public void setPublicId(PublicId value) {
        this.publicId = value;
    }

    /**
     * Gets the value of the preferredName property.
     * 
     * @return
     *     possible object is
     *     {@link PreferredName }
     *     
     */
    public PreferredName getPreferredName() {
        return preferredName;
    }

    /**
     * Sets the value of the preferredName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferredName }
     *     
     */
    public void setPreferredName(PreferredName value) {
        this.preferredName = value;
    }

    /**
     * Gets the value of the preferredDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredDefinition() {
        return preferredDefinition;
    }

    /**
     * Sets the value of the preferredDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredDefinition(String value) {
        this.preferredDefinition = value;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link LongName }
     *     
     */
    public LongName getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongName }
     *     
     */
    public void setLongName(LongName value) {
        this.longName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Version }
     *     
     */
    public Version getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Version }
     *     
     */
    public void setVersion(Version value) {
        this.version = value;
    }

    /**
     * Gets the value of the workflowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowStatus() {
        return workflowStatus;
    }

    /**
     * Sets the value of the workflowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowStatus(String value) {
        this.workflowStatus = value;
    }

    /**
     * Gets the value of the contextName property.
     * 
     * @return
     *     possible object is
     *     {@link ContextName }
     *     
     */
    public ContextName getContextName() {
        return contextName;
    }

    /**
     * Sets the value of the contextName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextName }
     *     
     */
    public void setContextName(ContextName value) {
        this.contextName = value;
    }

    /**
     * Gets the value of the contextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ContextVersion }
     *     
     */
    public ContextVersion getContextVersion() {
        return contextVersion;
    }

    /**
     * Sets the value of the contextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextVersion }
     *     
     */
    public void setContextVersion(ContextVersion value) {
        this.contextVersion = value;
    }

    /**
     * Gets the value of the conceptualDomain property.
     * 
     * @return
     *     possible object is
     *     {@link ConceptualDomain }
     *     
     */
    public ConceptualDomain getConceptualDomain() {
        return conceptualDomain;
    }

    /**
     * Sets the value of the conceptualDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConceptualDomain }
     *     
     */
    public void setConceptualDomain(ConceptualDomain value) {
        this.conceptualDomain = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatatype(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the valueDomainType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDomainType() {
        return valueDomainType;
    }

    /**
     * Sets the value of the valueDomainType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDomainType(String value) {
        this.valueDomainType = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfMeasure }
     *     
     */
    public UnitOfMeasure getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfMeasure }
     *     
     */
    public void setUnitOfMeasure(UnitOfMeasure value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the displayFormat property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayFormat }
     *     
     */
    public DisplayFormat getDisplayFormat() {
        return displayFormat;
    }

    /**
     * Sets the value of the displayFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayFormat }
     *     
     */
    public void setDisplayFormat(DisplayFormat value) {
        this.displayFormat = value;
    }

    /**
     * Gets the value of the maximumLength property.
     * 
     * @return
     *     possible object is
     *     {@link MaximumLength }
     *     
     */
    public MaximumLength getMaximumLength() {
        return maximumLength;
    }

    /**
     * Sets the value of the maximumLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaximumLength }
     *     
     */
    public void setMaximumLength(MaximumLength value) {
        this.maximumLength = value;
    }

    /**
     * Gets the value of the minimumLength property.
     * 
     * @return
     *     possible object is
     *     {@link MinimumLength }
     *     
     */
    public MinimumLength getMinimumLength() {
        return minimumLength;
    }

    /**
     * Sets the value of the minimumLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinimumLength }
     *     
     */
    public void setMinimumLength(MinimumLength value) {
        this.minimumLength = value;
    }

    /**
     * Gets the value of the decimalPlace property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalPlace }
     *     
     */
    public DecimalPlace getDecimalPlace() {
        return decimalPlace;
    }

    /**
     * Sets the value of the decimalPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalPlace }
     *     
     */
    public void setDecimalPlace(DecimalPlace value) {
        this.decimalPlace = value;
    }

    /**
     * Gets the value of the characterSetName property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterSetName }
     *     
     */
    public CharacterSetName getCharacterSetName() {
        return characterSetName;
    }

    /**
     * Sets the value of the characterSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterSetName }
     *     
     */
    public void setCharacterSetName(CharacterSetName value) {
        this.characterSetName = value;
    }

    /**
     * Gets the value of the maximumValue property.
     * 
     * @return
     *     possible object is
     *     {@link MaximumValue }
     *     
     */
    public MaximumValue getMaximumValue() {
        return maximumValue;
    }

    /**
     * Sets the value of the maximumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaximumValue }
     *     
     */
    public void setMaximumValue(MaximumValue value) {
        this.maximumValue = value;
    }

    /**
     * Gets the value of the minimumValue property.
     * 
     * @return
     *     possible object is
     *     {@link MinimumValue }
     *     
     */
    public MinimumValue getMinimumValue() {
        return minimumValue;
    }

    /**
     * Sets the value of the minimumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinimumValue }
     *     
     */
    public void setMinimumValue(MinimumValue value) {
        this.minimumValue = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Origin }
     *     
     */
    public Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origin }
     *     
     */
    public void setOrigin(Origin value) {
        this.origin = value;
    }

    /**
     * Gets the value of the representation property.
     * 
     * @return
     *     possible object is
     *     {@link Representation }
     *     
     */
    public Representation getRepresentation() {
        return representation;
    }

    /**
     * Sets the value of the representation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Representation }
     *     
     */
    public void setRepresentation(Representation value) {
        this.representation = value;
    }

    /**
     * Gets the value of the permissibleValues property.
     * 
     * @return
     *     possible object is
     *     {@link PermissibleValues }
     *     
     */
    public PermissibleValues getPermissibleValues() {
        return permissibleValues;
    }

    /**
     * Sets the value of the permissibleValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissibleValues }
     *     
     */
    public void setPermissibleValues(PermissibleValues value) {
        this.permissibleValues = value;
    }

    /**
     * Gets the value of the valueDomainConcepts property.
     * 
     * @return
     *     possible object is
     *     {@link ValueDomainConcepts }
     *     
     */
    public ValueDomainConcepts getValueDomainConcepts() {
        return valueDomainConcepts;
    }

    /**
     * Sets the value of the valueDomainConcepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueDomainConcepts }
     *     
     */
    public void setValueDomainConcepts(ValueDomainConcepts value) {
        this.valueDomainConcepts = value;
    }

}
