//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cdes_loader.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contextName",
    "contextVersion",
    "alternateName",
    "alternateNameType",
    "language"
})
@XmlRootElement(name = "ALTERNATENAMELIST_ITEM")
public class AlternateName {

    @XmlAttribute(name = "NULL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String _null;
    @XmlElement(name = "ContextName", required = true)
    protected ContextName contextName;
    @XmlElement(name = "ContextVersion", required = true)
    protected ContextVersion contextVersion;
    @XmlElement(name = "AlternateName", required = true)
    protected AlternateNameValue alternateName;
    @XmlElement(name = "AlternateNameType", required = true)
    protected AlternateNameType alternateNameType;
    @XmlElement(name = "Language", required = true)
    protected Language language;

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNULL() {
        if (_null == null) {
            return "TRUE";
        } else {
            return _null;
        }
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNULL(String value) {
        this._null = value;
    }

    /**
     * Gets the value of the contextName property.
     * 
     * @return
     *     possible object is
     *     {@link ContextName }
     *     
     */
    public ContextName getContextName() {
        return contextName;
    }

    /**
     * Sets the value of the contextName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextName }
     *     
     */
    public void setContextName(ContextName value) {
        this.contextName = value;
    }

    /**
     * Gets the value of the contextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ContextVersion }
     *     
     */
    public ContextVersion getContextVersion() {
        return contextVersion;
    }

    /**
     * Sets the value of the contextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextVersion }
     *     
     */
    public void setContextVersion(ContextVersion value) {
        this.contextVersion = value;
    }

    /**
     * Gets the value of the alternateName property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateNameValue }
     *     
     */
    public AlternateNameValue getAlternateName() {
        return alternateName;
    }

    /**
     * Sets the value of the alternateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateNameValue }
     *     
     */
    public void setAlternateName(AlternateNameValue value) {
        this.alternateName = value;
    }

    /**
     * Gets the value of the alternateNameType property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateNameType }
     *     
     */
    public AlternateNameType getAlternateNameType() {
        return alternateNameType;
    }

    /**
     * Sets the value of the alternateNameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateNameType }
     *     
     */
    public void setAlternateNameType(AlternateNameType value) {
        this.alternateNameType = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }

}
