//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cdes_loader.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "derivationType",
    "derivationTypeDescription",
    "methods",
    "rule",
    "concatenationCharacter",
    "componentDataElementsList"
})
@XmlRootElement(name = "DATAELEMENTDERIVATION")
public class DataElementDerivation {

    @XmlElement(name = "DerivationType", required = true)
    protected DerivationType derivationType;
    @XmlElement(name = "DerivationTypeDescription", required = true)
    protected DerivationTypeDescription derivationTypeDescription;
    @XmlElement(name = "Methods", required = true)
    protected Methods methods;
    @XmlElement(name = "Rule", required = true)
    protected Rule rule;
    @XmlElement(name = "ConcatenationCharacter", required = true)
    protected ConcatenationCharacter concatenationCharacter;
    @XmlElement(name = "ComponentDataElementsList", required = true)
    protected ComponentDataElementsList componentDataElementsList;

    /**
     * Gets the value of the derivationType property.
     * 
     * @return
     *     possible object is
     *     {@link DerivationType }
     *     
     */
    public DerivationType getDerivationType() {
        return derivationType;
    }

    /**
     * Sets the value of the derivationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivationType }
     *     
     */
    public void setDerivationType(DerivationType value) {
        this.derivationType = value;
    }

    /**
     * Gets the value of the derivationTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link DerivationTypeDescription }
     *     
     */
    public DerivationTypeDescription getDerivationTypeDescription() {
        return derivationTypeDescription;
    }

    /**
     * Sets the value of the derivationTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivationTypeDescription }
     *     
     */
    public void setDerivationTypeDescription(DerivationTypeDescription value) {
        this.derivationTypeDescription = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link Methods }
     *     
     */
    public Methods getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Methods }
     *     
     */
    public void setMethods(Methods value) {
        this.methods = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link Rule }
     *     
     */
    public Rule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rule }
     *     
     */
    public void setRule(Rule value) {
        this.rule = value;
    }

    /**
     * Gets the value of the concatenationCharacter property.
     * 
     * @return
     *     possible object is
     *     {@link ConcatenationCharacter }
     *     
     */
    public ConcatenationCharacter getConcatenationCharacter() {
        return concatenationCharacter;
    }

    /**
     * Sets the value of the concatenationCharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcatenationCharacter }
     *     
     */
    public void setConcatenationCharacter(ConcatenationCharacter value) {
        this.concatenationCharacter = value;
    }

    /**
     * Gets the value of the componentDataElementsList property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentDataElementsList }
     *     
     */
    public ComponentDataElementsList getComponentDataElementsList() {
        return componentDataElementsList;
    }

    /**
     * Sets the value of the componentDataElementsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentDataElementsList }
     *     
     */
    public void setComponentDataElementsList(ComponentDataElementsList value) {
        this.componentDataElementsList = value;
    }

}
