//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cdes_loader.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the examples package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: examples
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createOrigin() {
        return new Origin();
    }

    /**
     * Create an instance of {@link ValueDomainConcept }
     * 
     */
    public ValueDomainConcept createValueDomainConceptsITEM() {
        return new ValueDomainConcept();
    }

    /**
     * Create an instance of {@link DEFINITIONSOURCE }
     * 
     */
    public DEFINITIONSOURCE createDEFINITIONSOURCE() {
        return new DEFINITIONSOURCE();
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createORIGIN() {
        return new Origin();
    }

    /**
     * Create an instance of {@link ObjectClassQualifier }
     * 
     */
    public ObjectClassQualifier createObjectClassQualifier() {
        return new ObjectClassQualifier();
    }

    /**
     * Create an instance of {@link MaximumLength }
     * 
     */
    public MaximumLength createMaximumLength() {
        return new MaximumLength();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link AlternateNameType }
     * 
     */
    public AlternateNameType createAlternateNameType() {
        return new AlternateNameType();
    }

    /**
     * Create an instance of {@link ComponentDataElementsList }
     * 
     */
    public ComponentDataElementsList createComponentDataElementsList() {
        return new ComponentDataElementsList();
    }

    /**
     * Create an instance of {@link ComponentDataElement }
     * 
     */
    public ComponentDataElement createComponentDataElementsListITEM() {
        return new ComponentDataElement();
    }

    /**
     * Create an instance of {@link PVBEGINDATE }
     * 
     */
    public PVBEGINDATE createPVBEGINDATE() {
        return new PVBEGINDATE();
    }

    /**
     * Create an instance of {@link UnitOfMeasure }
     * 
     */
    public UnitOfMeasure createUnitOfMeasure() {
        return new UnitOfMeasure();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link PublicId }
     * 
     */
    public PublicId createPublicId() {
        return new PublicId();
    }

    /**
     * Create an instance of {@link ContextName }
     * 
     */
    public ContextName createContextName() {
        return new ContextName();
    }

    /**
     * Create an instance of {@link ContextVersion }
     * 
     */
    public ContextVersion createContextVersion() {
        return new ContextVersion();
    }

    /**
     * Create an instance of {@link PreferredName }
     * 
     */
    public PreferredName createPreferredName() {
        return new PreferredName();
    }

    /**
     * Create an instance of {@link LongName }
     * 
     */
    public LongName createLongName() {
        return new LongName();
    }

    /**
     * Create an instance of {@link ConceptDetails }
     * 
     */
    public ConceptDetails createConceptDetails() {
        return new ConceptDetails();
    }

    /**
     * Create an instance of {@link PVENDDATE }
     * 
     */
    public PVENDDATE createPVENDDATE() {
        return new PVENDDATE();
    }

    /**
     * Create an instance of {@link ValueDomainConcepts }
     * 
     */
    public ValueDomainConcepts createValueDomainConcepts() {
        return new ValueDomainConcepts();
    }

    /**
     * Create an instance of {@link ConcatenationCharacter }
     * 
     */
    public ConcatenationCharacter createConcatenationCharacter() {
        return new ConcatenationCharacter();
    }

    /**
     * Create an instance of {@link DataElementsList }
     * 
     */
    public DataElementsList createDataElementsList() {
        return new DataElementsList();
    }

    /**
     * Create an instance of {@link DataElement }
     * 
     */
    public DataElement createDataElement() {
        return new DataElement();
    }

    /**
     * Create an instance of {@link DecimalPlace }
     * 
     */
    public DecimalPlace createDecimalPlace() {
        return new DecimalPlace();
    }

    /**
     * Create an instance of {@link PermissibleValues }
     * 
     */
    public PermissibleValues createPermissibleValues() {
        return new PermissibleValues();
    }

    /**
     * Create an instance of {@link PermissibleValue }
     * 
     */
    public PermissibleValue createPermissibleValuesITEM() {
        return new PermissibleValue();
    }

    /**
     * Create an instance of {@link Concept }
     * 
     */
    public Concept createConceptDetailsITEM() {
        return new Concept();
    }

    /**
     * Create an instance of {@link ClassificationScheme }
     * 
     */
    public ClassificationScheme createClassificationScheme() {
        return new ClassificationScheme();
    }

    /**
     * Create an instance of {@link ConceptualDomain }
     * 
     */
    public ConceptualDomain createConceptualDomain() {
        return new ConceptualDomain();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Methods }
     * 
     */
    public Methods createMethods() {
        return new Methods();
    }

    /**
     * Create an instance of {@link OrganizationName }
     * 
     */
    public OrganizationName createOrganizationName() {
        return new OrganizationName();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createCLASSIFICATIONSLISTITEM() {
        return new Classification();
    }

    /**
     * Create an instance of {@link CharacterSetName }
     * 
     */
    public CharacterSetName createCharacterSetName() {
        return new CharacterSetName();
    }

    /**
     * Create an instance of {@link MinimumLength }
     * 
     */
    public MinimumLength createMinimumLength() {
        return new MinimumLength();
    }

    /**
     * Create an instance of {@link MaximumValue }
     * 
     */
    public MaximumValue createMaximumValue() {
        return new MaximumValue();
    }

    /**
     * Create an instance of {@link MEANINGCONCEPTS }
     * 
     */
    public MEANINGCONCEPTS createMEANINGCONCEPTS() {
        return new MEANINGCONCEPTS();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link REFERENCEDOCUMENTSLIST }
     * 
     */
    public REFERENCEDOCUMENTSLIST createREFERENCEDOCUMENTSLIST() {
        return new REFERENCEDOCUMENTSLIST();
    }

    /**
     * Create an instance of {@link ReferenceDocument }
     * 
     */
    public ReferenceDocument createREFERENCEDOCUMENTSLISTITEM() {
        return new ReferenceDocument();
    }

    /**
     * Create an instance of {@link REGISTRATIONSTATUS }
     * 
     */
    public REGISTRATIONSTATUS createREGISTRATIONSTATUS() {
        return new REGISTRATIONSTATUS();
    }

    /**
     * Create an instance of {@link DataElementConcept }
     * 
     */
    public DataElementConcept createDataElementConcept() {
        return new DataElementConcept();
    }

    /**
     * Create an instance of {@link ValueDomain }
     * 
     */
    public ValueDomain createVALUEDOMAIN() {
        return new ValueDomain();
    }

    /**
     * Create an instance of {@link CLASSIFICATIONSLIST }
     * 
     */
    public CLASSIFICATIONSLIST createCLASSIFICATIONSLIST() {
        return new CLASSIFICATIONSLIST();
    }

    /**
     * Create an instance of {@link ALTERNATENAMELIST }
     * 
     */
    public ALTERNATENAMELIST createALTERNATENAMELIST() {
        return new ALTERNATENAMELIST();
    }

    /**
     * Create an instance of {@link DataElementDerivation }
     * 
     */
    public DataElementDerivation createDataElementDerivation() {
        return new DataElementDerivation();
    }

    /**
     * Create an instance of {@link AlternateName }
     * 
     */
    public AlternateName createALTERNATENAMELISTITEM() {
        return new AlternateName();
    }

    /**
     * Create an instance of {@link DerivationType }
     * 
     */
    public DerivationType createDerivationType() {
        return new DerivationType();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link ObjectClass }
     * 
     */
    public ObjectClass createObjectClass() {
        return new ObjectClass();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link PropertyQualifier }
     * 
     */
    public PropertyQualifier createPropertyQualifier() {
        return new PropertyQualifier();
    }

    /**
     * Create an instance of {@link AlternateName }
     * 
     */
    public AlternateName createAlternateName() {
        return new AlternateName();
    }

    /**
     * Create an instance of {@link DisplayOrder }
     * 
     */
    public DisplayOrder createDisplayOrder() {
        return new DisplayOrder();
    }

    /**
     * Create an instance of {@link DerivationTypeDescription }
     * 
     */
    public DerivationTypeDescription createDerivationTypeDescription() {
        return new DerivationTypeDescription();
    }

    /**
     * Create an instance of {@link DisplayFormat }
     * 
     */
    public DisplayFormat createDisplayFormat() {
        return new DisplayFormat();
    }

    /**
     * Create an instance of {@link DocumentText }
     * 
     */
    public DocumentText createDocumentText() {
        return new DocumentText();
    }

    /**
     * Create an instance of {@link MinimumValue }
     * 
     */
    public MinimumValue createMinimumValue() {
        return new MinimumValue();
    }

}
