//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 05:38:06 PM PDT 
//


package org.metadatacenter.cadsr.cdes_loader.cadsr_objects.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validValue",
    "valueMeaning",
    "meaningDescription",
    "meaningConcepts",
    "pvBeginDate",
    "pvEndDate",
    "vmPublicId",
    "vmVersion"
})
@XmlRootElement(name = "PermissibleValues_ITEM")
public class PermissibleValue {

    @XmlElement(name = "VALIDVALUE", required = true)
    protected String validValue;
    @XmlElement(name = "VALUEMEANING", required = true)
    protected String valueMeaning;
    @XmlElement(name = "MEANINGDESCRIPTION", required = true)
    protected String meaningDescription;
    @XmlElement(name = "MEANINGCONCEPTS", required = true)
    protected MEANINGCONCEPTS meaningConcepts;
    @XmlElement(name = "PVBEGINDATE", required = true)
    protected PVBEGINDATE pvBeginDate;
    @XmlElement(name = "PVENDDATE", required = true)
    protected PVENDDATE pvEndDate;
    @XmlElement(name = "VMPUBLICID", required = true)
    protected String vmPublicId;
    @XmlElement(name = "VMVERSION", required = true)
    protected String vmVersion;

    public String getValidValue()
    {
        return validValue;
    }

    public void setValidValue(String validValue)
    {
        this.validValue = validValue;
    }

    public String getValueMeaning()
    {
        return valueMeaning;
    }

    public void setValueMeaning(String valueMeaning)
    {
        this.valueMeaning = valueMeaning;
    }

    public String getMeaningDescription()
    {
        return meaningDescription;
    }

    public void setMeaningDescription(String meaningDescription)
    {
        this.meaningDescription = meaningDescription;
    }

    public MEANINGCONCEPTS getMeaningConcepts()
    {
        return meaningConcepts;
    }

    public void setMeaningConcepts(MEANINGCONCEPTS meaningConcepts)
    {
        this.meaningConcepts = meaningConcepts;
    }

    public PVBEGINDATE getPvBeginDate()
    {
        return pvBeginDate;
    }

    public void setPvBeginDate(PVBEGINDATE pvBeginDate)
    {
        this.pvBeginDate = pvBeginDate;
    }

    public PVENDDATE getPvEndDate()
    {
        return pvEndDate;
    }

    public void setPvEndDate(PVENDDATE pvEndDate)
    {
        this.pvEndDate = pvEndDate;
    }

    public String getVmPublicId()
    {
        return vmPublicId;
    }

    public void setVmPublicId(String vmPublicId)
    {
        this.vmPublicId = vmPublicId;
    }

    public String getVmVersion()
    {
        return vmVersion;
    }

    public void setVmVersion(String vmVersion)
    {
        this.vmVersion = vmVersion;
    }
}
